### ISSUE TITLE
Linea del Tiempo web Kevin Osorio 1 "B"

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-7-KevinOsorio23143#1]
[Linea del tiempo web Kevin Osorio Aparicio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-KevinOsorio23143/files/9796282/Linea.del.tiempo.web.Kevin.Osorio.Aparicio.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 17.2% de un 20% , debido a que cuentas con demasiada información irrelevante, de igual forma dificulta el entendimiento.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
